sonar.projectKey=rubenillob-dot_sonar-practica
sonar.organization=rubenillob-dot
sonar.host.url=https://sonarcloud.io
sonar.token=d43205c2f9708b23c4c9e3443fde654ad426d0ff
sonar.sources=src/main/java
sonar.java.source=11
sonar.coverage.exclusions=**/*.java